#!/usr/bin/env node
import { readFile } from "node:fs/promises";
import { pathToFileURL } from "node:url";
import { parsePolicyDocumentText } from "@letscoding/policy-contract";
import { artifactValidationPolicyFromDocument } from "./policy.js";
import { inspectArtifact } from "./node.js";
export async function runArtifactValidatorCli(argv, io = process) {
    try {
        const parsed = parseArguments(argv);
        const policyText = await readFile(parsed.policyPath, "utf8");
        const policyResult = parsePolicyDocumentText(policyText);
        if (!policyResult.ok) {
            io.stderr.write(`${JSON.stringify({ error: { code: "POLICY_INVALID", issues: policyResult.issues } })}\n`);
            return 2;
        }
        const result = await inspectArtifact({
            kind: parsed.kind,
            inputPath: parsed.inputPath,
            policy: artifactValidationPolicyFromDocument(policyResult.value),
        });
        writeJson(io.stdout, result);
        return result.pass ? 0 : 1;
    }
    catch (error) {
        io.stderr.write(`${JSON.stringify({ error: { code: "CLI_INTERNAL_ERROR", message: safeErrorMessage(error) } })}\n`);
        return 2;
    }
}
function parseArguments(argv) {
    let policyPath;
    let zipPath;
    let directoryPath;
    for (let index = 0; index < argv.length; index += 1) {
        const argument = argv[index];
        const value = argv[index + 1];
        if (argument === "--policy" && value !== undefined) {
            policyPath = value;
            index += 1;
        }
        else if (argument === "--zip" && value !== undefined) {
            zipPath = value;
            index += 1;
        }
        else if (argument === "--directory" && value !== undefined) {
            directoryPath = value;
            index += 1;
        }
        else {
            throw new Error("Usage: lounge-artifact-validate --policy <snapshot.json> (--zip <file.zip> | --directory <output-dir>)");
        }
    }
    if (policyPath === undefined ||
        (zipPath === undefined) === (directoryPath === undefined)) {
        throw new Error("Usage: lounge-artifact-validate --policy <snapshot.json> (--zip <file.zip> | --directory <output-dir>)");
    }
    return zipPath === undefined
        ? { policyPath, kind: "directory", inputPath: directoryPath }
        : { policyPath, kind: "zip", inputPath: zipPath };
}
function writeJson(output, result) {
    output.write(`${JSON.stringify(result)}\n`);
}
function safeErrorMessage(error) {
    if (!(error instanceof Error))
        return "알 수 없는 내부 오류입니다.";
    // Only messages generated by this CLI are expected here. Filesystem errors
    // can contain local paths, so do not reflect arbitrary exception messages.
    return error.message.startsWith("Usage:")
        ? error.message
        : "artifact 검사 중 내부 오류가 발생했습니다.";
}
const invokedPath = process.argv[1];
if (invokedPath !== undefined &&
    import.meta.url === pathToFileURL(invokedPath).href) {
    process.exitCode = await runArtifactValidatorCli(process.argv.slice(2));
}
//# sourceMappingURL=cli.js.map